/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:5363310a-f9ec-4eda-b35d-7620e597359c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_jxsnevIQR",
    "aws_user_pools_web_client_id": "586jin3q9v8g8sk02km6rrv6t6",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://gaf5hn4dxvhixhochq2ngztsgm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qfq5r7lhw5bvfoclycdfmjzcam",
    "aws_user_files_s3_bucket": "imbbucket101159-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
